#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR_YieldmaxTools
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mdr")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHistoricalDividendData(HistoricalDividendData instance);
    partial void UpdateHistoricalDividendData(HistoricalDividendData instance);
    partial void DeleteHistoricalDividendData(HistoricalDividendData instance);
    partial void InsertHistoricalDividendDataAdjustedToWeekly(HistoricalDividendDataAdjustedToWeekly instance);
    partial void UpdateHistoricalDividendDataAdjustedToWeekly(HistoricalDividendDataAdjustedToWeekly instance);
    partial void DeleteHistoricalDividendDataAdjustedToWeekly(HistoricalDividendDataAdjustedToWeekly instance);
    partial void InsertHistoricalTickData1D(HistoricalTickData1D instance);
    partial void UpdateHistoricalTickData1D(HistoricalTickData1D instance);
    partial void DeleteHistoricalTickData1D(HistoricalTickData1D instance);
    partial void InsertHistoricalTickData1WK(HistoricalTickData1WK instance);
    partial void UpdateHistoricalTickData1WK(HistoricalTickData1WK instance);
    partial void DeleteHistoricalTickData1WK(HistoricalTickData1WK instance);
    partial void Insertyf1_profile(yf1_profile instance);
    partial void Updateyf1_profile(yf1_profile instance);
    partial void Deleteyf1_profile(yf1_profile instance);
    partial void InsertHistoricalStockSplit(HistoricalStockSplit instance);
    partial void UpdateHistoricalStockSplit(HistoricalStockSplit instance);
    partial void DeleteHistoricalStockSplit(HistoricalStockSplit instance);
    #endregion
		
		public dbDataContext() : 
				base(global::MDR_YieldmaxTools.Properties.Settings.Default.mdrConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HistoricalDividendData> HistoricalDividendDatas
		{
			get
			{
				return this.GetTable<HistoricalDividendData>();
			}
		}
		
		public System.Data.Linq.Table<HistoricalDividendDataAdjustedToWeekly> HistoricalDividendDataAdjustedToWeeklies
		{
			get
			{
				return this.GetTable<HistoricalDividendDataAdjustedToWeekly>();
			}
		}
		
		public System.Data.Linq.Table<HistoricalTickData1D> HistoricalTickData1Ds
		{
			get
			{
				return this.GetTable<HistoricalTickData1D>();
			}
		}
		
		public System.Data.Linq.Table<HistoricalTickData1WK> HistoricalTickData1WKs
		{
			get
			{
				return this.GetTable<HistoricalTickData1WK>();
			}
		}
		
		public System.Data.Linq.Table<yf1_profile> yf1_profiles
		{
			get
			{
				return this.GetTable<yf1_profile>();
			}
		}
		
		public System.Data.Linq.Table<ForGrid_AppendAdjClose> ForGrid_AppendAdjCloses
		{
			get
			{
				return this.GetTable<ForGrid_AppendAdjClose>();
			}
		}
		
		public System.Data.Linq.Table<HistoricalStockSplit> HistoricalStockSplits
		{
			get
			{
				return this.GetTable<HistoricalStockSplit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricalDividendData")]
	public partial class HistoricalDividendData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private System.DateTime _timestamp;
		
		private System.Nullable<double> _dividend;
		
		private EntityRef<yf1_profile> _yf1_profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OndividendChanging(System.Nullable<double> value);
    partial void OndividendChanged();
    #endregion
		
		public HistoricalDividendData()
		{
			this._yf1_profile = default(EntityRef<yf1_profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					if (this._yf1_profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dividend", DbType="Float")]
		public System.Nullable<double> dividend
		{
			get
			{
				return this._dividend;
			}
			set
			{
				if ((this._dividend != value))
				{
					this.OndividendChanging(value);
					this.SendPropertyChanging();
					this._dividend = value;
					this.SendPropertyChanged("dividend");
					this.OndividendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalDividendData", Storage="_yf1_profile", ThisKey="symbol", OtherKey="symbol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public yf1_profile yf1_profile
		{
			get
			{
				return this._yf1_profile.Entity;
			}
			set
			{
				yf1_profile previousValue = this._yf1_profile.Entity;
				if (((previousValue != value) 
							|| (this._yf1_profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yf1_profile.Entity = null;
						previousValue.HistoricalDividendDatas.Remove(this);
					}
					this._yf1_profile.Entity = value;
					if ((value != null))
					{
						value.HistoricalDividendDatas.Add(this);
						this._symbol = value.symbol;
					}
					else
					{
						this._symbol = default(string);
					}
					this.SendPropertyChanged("yf1_profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricalDividendDataAdjustedToWeekly")]
	public partial class HistoricalDividendDataAdjustedToWeekly : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private System.DateTime _timestamp;
		
		private System.Nullable<double> _dividend;
		
		private EntityRef<yf1_profile> _yf1_profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OndividendChanging(System.Nullable<double> value);
    partial void OndividendChanged();
    #endregion
		
		public HistoricalDividendDataAdjustedToWeekly()
		{
			this._yf1_profile = default(EntityRef<yf1_profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					if (this._yf1_profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dividend", DbType="Float")]
		public System.Nullable<double> dividend
		{
			get
			{
				return this._dividend;
			}
			set
			{
				if ((this._dividend != value))
				{
					this.OndividendChanging(value);
					this.SendPropertyChanging();
					this._dividend = value;
					this.SendPropertyChanged("dividend");
					this.OndividendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalDividendDataAdjustedToWeekly", Storage="_yf1_profile", ThisKey="symbol", OtherKey="symbol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public yf1_profile yf1_profile
		{
			get
			{
				return this._yf1_profile.Entity;
			}
			set
			{
				yf1_profile previousValue = this._yf1_profile.Entity;
				if (((previousValue != value) 
							|| (this._yf1_profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yf1_profile.Entity = null;
						previousValue.HistoricalDividendDataAdjustedToWeeklies.Remove(this);
					}
					this._yf1_profile.Entity = value;
					if ((value != null))
					{
						value.HistoricalDividendDataAdjustedToWeeklies.Add(this);
						this._symbol = value.symbol;
					}
					else
					{
						this._symbol = default(string);
					}
					this.SendPropertyChanged("yf1_profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricalTickData1D")]
	public partial class HistoricalTickData1D : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private System.DateTime _timestamp;
		
		private System.Nullable<double> _open;
		
		private System.Nullable<double> _high;
		
		private System.Nullable<double> _low;
		
		private System.Nullable<double> _close;
		
		private System.Nullable<double> _adjustedClose;
		
		private System.Nullable<int> _volume;
		
		private EntityRef<yf1_profile> _yf1_profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OnopenChanging(System.Nullable<double> value);
    partial void OnopenChanged();
    partial void OnhighChanging(System.Nullable<double> value);
    partial void OnhighChanged();
    partial void OnlowChanging(System.Nullable<double> value);
    partial void OnlowChanged();
    partial void OncloseChanging(System.Nullable<double> value);
    partial void OncloseChanged();
    partial void OnadjustedCloseChanging(System.Nullable<double> value);
    partial void OnadjustedCloseChanged();
    partial void OnvolumeChanging(System.Nullable<int> value);
    partial void OnvolumeChanged();
    #endregion
		
		public HistoricalTickData1D()
		{
			this._yf1_profile = default(EntityRef<yf1_profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					if (this._yf1_profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[open]", Storage="_open", DbType="Float")]
		public System.Nullable<double> open
		{
			get
			{
				return this._open;
			}
			set
			{
				if ((this._open != value))
				{
					this.OnopenChanging(value);
					this.SendPropertyChanging();
					this._open = value;
					this.SendPropertyChanged("open");
					this.OnopenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_high", DbType="Float")]
		public System.Nullable<double> high
		{
			get
			{
				return this._high;
			}
			set
			{
				if ((this._high != value))
				{
					this.OnhighChanging(value);
					this.SendPropertyChanging();
					this._high = value;
					this.SendPropertyChanged("high");
					this.OnhighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_low", DbType="Float")]
		public System.Nullable<double> low
		{
			get
			{
				return this._low;
			}
			set
			{
				if ((this._low != value))
				{
					this.OnlowChanging(value);
					this.SendPropertyChanging();
					this._low = value;
					this.SendPropertyChanged("low");
					this.OnlowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[close]", Storage="_close", DbType="Float")]
		public System.Nullable<double> close
		{
			get
			{
				return this._close;
			}
			set
			{
				if ((this._close != value))
				{
					this.OncloseChanging(value);
					this.SendPropertyChanging();
					this._close = value;
					this.SendPropertyChanged("close");
					this.OncloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjustedClose", DbType="Float")]
		public System.Nullable<double> adjustedClose
		{
			get
			{
				return this._adjustedClose;
			}
			set
			{
				if ((this._adjustedClose != value))
				{
					this.OnadjustedCloseChanging(value);
					this.SendPropertyChanging();
					this._adjustedClose = value;
					this.SendPropertyChanged("adjustedClose");
					this.OnadjustedCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="Int")]
		public System.Nullable<int> volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalTickData1D", Storage="_yf1_profile", ThisKey="symbol", OtherKey="symbol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public yf1_profile yf1_profile
		{
			get
			{
				return this._yf1_profile.Entity;
			}
			set
			{
				yf1_profile previousValue = this._yf1_profile.Entity;
				if (((previousValue != value) 
							|| (this._yf1_profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yf1_profile.Entity = null;
						previousValue.HistoricalTickData1Ds.Remove(this);
					}
					this._yf1_profile.Entity = value;
					if ((value != null))
					{
						value.HistoricalTickData1Ds.Add(this);
						this._symbol = value.symbol;
					}
					else
					{
						this._symbol = default(string);
					}
					this.SendPropertyChanged("yf1_profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricalTickData1WK")]
	public partial class HistoricalTickData1WK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private System.DateTime _timestamp;
		
		private System.Nullable<double> _open;
		
		private System.Nullable<double> _high;
		
		private System.Nullable<double> _low;
		
		private System.Nullable<double> _close;
		
		private System.Nullable<double> _adjustedClose;
		
		private System.Nullable<int> _volume;
		
		private EntityRef<yf1_profile> _yf1_profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OnopenChanging(System.Nullable<double> value);
    partial void OnopenChanged();
    partial void OnhighChanging(System.Nullable<double> value);
    partial void OnhighChanged();
    partial void OnlowChanging(System.Nullable<double> value);
    partial void OnlowChanged();
    partial void OncloseChanging(System.Nullable<double> value);
    partial void OncloseChanged();
    partial void OnadjustedCloseChanging(System.Nullable<double> value);
    partial void OnadjustedCloseChanged();
    partial void OnvolumeChanging(System.Nullable<int> value);
    partial void OnvolumeChanged();
    #endregion
		
		public HistoricalTickData1WK()
		{
			this._yf1_profile = default(EntityRef<yf1_profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					if (this._yf1_profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[open]", Storage="_open", DbType="Float")]
		public System.Nullable<double> open
		{
			get
			{
				return this._open;
			}
			set
			{
				if ((this._open != value))
				{
					this.OnopenChanging(value);
					this.SendPropertyChanging();
					this._open = value;
					this.SendPropertyChanged("open");
					this.OnopenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_high", DbType="Float")]
		public System.Nullable<double> high
		{
			get
			{
				return this._high;
			}
			set
			{
				if ((this._high != value))
				{
					this.OnhighChanging(value);
					this.SendPropertyChanging();
					this._high = value;
					this.SendPropertyChanged("high");
					this.OnhighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_low", DbType="Float")]
		public System.Nullable<double> low
		{
			get
			{
				return this._low;
			}
			set
			{
				if ((this._low != value))
				{
					this.OnlowChanging(value);
					this.SendPropertyChanging();
					this._low = value;
					this.SendPropertyChanged("low");
					this.OnlowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[close]", Storage="_close", DbType="Float")]
		public System.Nullable<double> close
		{
			get
			{
				return this._close;
			}
			set
			{
				if ((this._close != value))
				{
					this.OncloseChanging(value);
					this.SendPropertyChanging();
					this._close = value;
					this.SendPropertyChanged("close");
					this.OncloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjustedClose", DbType="Float")]
		public System.Nullable<double> adjustedClose
		{
			get
			{
				return this._adjustedClose;
			}
			set
			{
				if ((this._adjustedClose != value))
				{
					this.OnadjustedCloseChanging(value);
					this.SendPropertyChanging();
					this._adjustedClose = value;
					this.SendPropertyChanged("adjustedClose");
					this.OnadjustedCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="Int")]
		public System.Nullable<int> volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalTickData1WK", Storage="_yf1_profile", ThisKey="symbol", OtherKey="symbol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public yf1_profile yf1_profile
		{
			get
			{
				return this._yf1_profile.Entity;
			}
			set
			{
				yf1_profile previousValue = this._yf1_profile.Entity;
				if (((previousValue != value) 
							|| (this._yf1_profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yf1_profile.Entity = null;
						previousValue.HistoricalTickData1WKs.Remove(this);
					}
					this._yf1_profile.Entity = value;
					if ((value != null))
					{
						value.HistoricalTickData1WKs.Add(this);
						this._symbol = value.symbol;
					}
					else
					{
						this._symbol = default(string);
					}
					this.SendPropertyChanged("yf1_profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yf1_profile")]
	public partial class yf1_profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private string _styleBoxUrl;
		
		private string _family;
		
		private string _categoryName;
		
		private string _legalType;
		
		private string _longBusinessSummary;
		
		private EntitySet<HistoricalDividendData> _HistoricalDividendDatas;
		
		private EntitySet<HistoricalDividendDataAdjustedToWeekly> _HistoricalDividendDataAdjustedToWeeklies;
		
		private EntitySet<HistoricalTickData1D> _HistoricalTickData1Ds;
		
		private EntitySet<HistoricalTickData1WK> _HistoricalTickData1WKs;
		
		private EntitySet<HistoricalStockSplit> _HistoricalStockSplits;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OnstyleBoxUrlChanging(string value);
    partial void OnstyleBoxUrlChanged();
    partial void OnfamilyChanging(string value);
    partial void OnfamilyChanged();
    partial void OncategoryNameChanging(string value);
    partial void OncategoryNameChanged();
    partial void OnlegalTypeChanging(string value);
    partial void OnlegalTypeChanged();
    partial void OnlongBusinessSummaryChanging(string value);
    partial void OnlongBusinessSummaryChanged();
    #endregion
		
		public yf1_profile()
		{
			this._HistoricalDividendDatas = new EntitySet<HistoricalDividendData>(new Action<HistoricalDividendData>(this.attach_HistoricalDividendDatas), new Action<HistoricalDividendData>(this.detach_HistoricalDividendDatas));
			this._HistoricalDividendDataAdjustedToWeeklies = new EntitySet<HistoricalDividendDataAdjustedToWeekly>(new Action<HistoricalDividendDataAdjustedToWeekly>(this.attach_HistoricalDividendDataAdjustedToWeeklies), new Action<HistoricalDividendDataAdjustedToWeekly>(this.detach_HistoricalDividendDataAdjustedToWeeklies));
			this._HistoricalTickData1Ds = new EntitySet<HistoricalTickData1D>(new Action<HistoricalTickData1D>(this.attach_HistoricalTickData1Ds), new Action<HistoricalTickData1D>(this.detach_HistoricalTickData1Ds));
			this._HistoricalTickData1WKs = new EntitySet<HistoricalTickData1WK>(new Action<HistoricalTickData1WK>(this.attach_HistoricalTickData1WKs), new Action<HistoricalTickData1WK>(this.detach_HistoricalTickData1WKs));
			this._HistoricalStockSplits = new EntitySet<HistoricalStockSplit>(new Action<HistoricalStockSplit>(this.attach_HistoricalStockSplits), new Action<HistoricalStockSplit>(this.detach_HistoricalStockSplits));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_styleBoxUrl", DbType="NVarChar(MAX)")]
		public string styleBoxUrl
		{
			get
			{
				return this._styleBoxUrl;
			}
			set
			{
				if ((this._styleBoxUrl != value))
				{
					this.OnstyleBoxUrlChanging(value);
					this.SendPropertyChanging();
					this._styleBoxUrl = value;
					this.SendPropertyChanged("styleBoxUrl");
					this.OnstyleBoxUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family", DbType="NVarChar(MAX)")]
		public string family
		{
			get
			{
				return this._family;
			}
			set
			{
				if ((this._family != value))
				{
					this.OnfamilyChanging(value);
					this.SendPropertyChanging();
					this._family = value;
					this.SendPropertyChanged("family");
					this.OnfamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryName", DbType="NVarChar(MAX)")]
		public string categoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				if ((this._categoryName != value))
				{
					this.OncategoryNameChanging(value);
					this.SendPropertyChanging();
					this._categoryName = value;
					this.SendPropertyChanged("categoryName");
					this.OncategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_legalType", DbType="NVarChar(MAX)")]
		public string legalType
		{
			get
			{
				return this._legalType;
			}
			set
			{
				if ((this._legalType != value))
				{
					this.OnlegalTypeChanging(value);
					this.SendPropertyChanging();
					this._legalType = value;
					this.SendPropertyChanged("legalType");
					this.OnlegalTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longBusinessSummary", DbType="NVarChar(MAX)")]
		public string longBusinessSummary
		{
			get
			{
				return this._longBusinessSummary;
			}
			set
			{
				if ((this._longBusinessSummary != value))
				{
					this.OnlongBusinessSummaryChanging(value);
					this.SendPropertyChanging();
					this._longBusinessSummary = value;
					this.SendPropertyChanged("longBusinessSummary");
					this.OnlongBusinessSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalDividendData", Storage="_HistoricalDividendDatas", ThisKey="symbol", OtherKey="symbol")]
		public EntitySet<HistoricalDividendData> HistoricalDividendDatas
		{
			get
			{
				return this._HistoricalDividendDatas;
			}
			set
			{
				this._HistoricalDividendDatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalDividendDataAdjustedToWeekly", Storage="_HistoricalDividendDataAdjustedToWeeklies", ThisKey="symbol", OtherKey="symbol")]
		public EntitySet<HistoricalDividendDataAdjustedToWeekly> HistoricalDividendDataAdjustedToWeeklies
		{
			get
			{
				return this._HistoricalDividendDataAdjustedToWeeklies;
			}
			set
			{
				this._HistoricalDividendDataAdjustedToWeeklies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalTickData1D", Storage="_HistoricalTickData1Ds", ThisKey="symbol", OtherKey="symbol")]
		public EntitySet<HistoricalTickData1D> HistoricalTickData1Ds
		{
			get
			{
				return this._HistoricalTickData1Ds;
			}
			set
			{
				this._HistoricalTickData1Ds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalTickData1WK", Storage="_HistoricalTickData1WKs", ThisKey="symbol", OtherKey="symbol")]
		public EntitySet<HistoricalTickData1WK> HistoricalTickData1WKs
		{
			get
			{
				return this._HistoricalTickData1WKs;
			}
			set
			{
				this._HistoricalTickData1WKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalStockSplit", Storage="_HistoricalStockSplits", ThisKey="symbol", OtherKey="symbol")]
		public EntitySet<HistoricalStockSplit> HistoricalStockSplits
		{
			get
			{
				return this._HistoricalStockSplits;
			}
			set
			{
				this._HistoricalStockSplits.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistoricalDividendDatas(HistoricalDividendData entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = this;
		}
		
		private void detach_HistoricalDividendDatas(HistoricalDividendData entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = null;
		}
		
		private void attach_HistoricalDividendDataAdjustedToWeeklies(HistoricalDividendDataAdjustedToWeekly entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = this;
		}
		
		private void detach_HistoricalDividendDataAdjustedToWeeklies(HistoricalDividendDataAdjustedToWeekly entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = null;
		}
		
		private void attach_HistoricalTickData1Ds(HistoricalTickData1D entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = this;
		}
		
		private void detach_HistoricalTickData1Ds(HistoricalTickData1D entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = null;
		}
		
		private void attach_HistoricalTickData1WKs(HistoricalTickData1WK entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = this;
		}
		
		private void detach_HistoricalTickData1WKs(HistoricalTickData1WK entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = null;
		}
		
		private void attach_HistoricalStockSplits(HistoricalStockSplit entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = this;
		}
		
		private void detach_HistoricalStockSplits(HistoricalStockSplit entity)
		{
			this.SendPropertyChanging();
			entity.yf1_profile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ForGrid_AppendAdjClose")]
	public partial class ForGrid_AppendAdjClose
	{
		
		private string _symbol;
		
		private System.Nullable<System.DateTime> _minDate;
		
		private System.Nullable<double> _adjustedClose;
		
		public ForGrid_AppendAdjClose()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					this._symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minDate", DbType="Date")]
		public System.Nullable<System.DateTime> minDate
		{
			get
			{
				return this._minDate;
			}
			set
			{
				if ((this._minDate != value))
				{
					this._minDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adjustedClose", DbType="Float")]
		public System.Nullable<double> adjustedClose
		{
			get
			{
				return this._adjustedClose;
			}
			set
			{
				if ((this._adjustedClose != value))
				{
					this._adjustedClose = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricalStockSplit")]
	public partial class HistoricalStockSplit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _symbol;
		
		private System.DateTime _timestamp;
		
		private double _numerator;
		
		private double _denominator;
		
		private string _splitRatio;
		
		private EntityRef<yf1_profile> _yf1_profile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsymbolChanging(string value);
    partial void OnsymbolChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OnnumeratorChanging(double value);
    partial void OnnumeratorChanged();
    partial void OndenominatorChanging(double value);
    partial void OndenominatorChanged();
    partial void OnsplitRatioChanging(string value);
    partial void OnsplitRatioChanged();
    #endregion
		
		public HistoricalStockSplit()
		{
			this._yf1_profile = default(EntityRef<yf1_profile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					if (this._yf1_profile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsymbolChanging(value);
					this.SendPropertyChanging();
					this._symbol = value;
					this.SendPropertyChanged("symbol");
					this.OnsymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerator", DbType="Float NOT NULL")]
		public double numerator
		{
			get
			{
				return this._numerator;
			}
			set
			{
				if ((this._numerator != value))
				{
					this.OnnumeratorChanging(value);
					this.SendPropertyChanging();
					this._numerator = value;
					this.SendPropertyChanged("numerator");
					this.OnnumeratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denominator", DbType="Float NOT NULL")]
		public double denominator
		{
			get
			{
				return this._denominator;
			}
			set
			{
				if ((this._denominator != value))
				{
					this.OndenominatorChanging(value);
					this.SendPropertyChanging();
					this._denominator = value;
					this.SendPropertyChanged("denominator");
					this.OndenominatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_splitRatio", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string splitRatio
		{
			get
			{
				return this._splitRatio;
			}
			set
			{
				if ((this._splitRatio != value))
				{
					this.OnsplitRatioChanging(value);
					this.SendPropertyChanging();
					this._splitRatio = value;
					this.SendPropertyChanged("splitRatio");
					this.OnsplitRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yf1_profile_HistoricalStockSplit", Storage="_yf1_profile", ThisKey="symbol", OtherKey="symbol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public yf1_profile yf1_profile
		{
			get
			{
				return this._yf1_profile.Entity;
			}
			set
			{
				yf1_profile previousValue = this._yf1_profile.Entity;
				if (((previousValue != value) 
							|| (this._yf1_profile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yf1_profile.Entity = null;
						previousValue.HistoricalStockSplits.Remove(this);
					}
					this._yf1_profile.Entity = value;
					if ((value != null))
					{
						value.HistoricalStockSplits.Add(this);
						this._symbol = value.symbol;
					}
					else
					{
						this._symbol = default(string);
					}
					this.SendPropertyChanged("yf1_profile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
